processout/processout-android

app/build.gradle, app/src/main/java/com/processout/processoutexample/MainActivity.java, build.gradle, gradle/wrapper/gradle-wrapper.properties, processout-sdk/build.gradle, processout-sdk/src/main/java/com/processout/processout_sdk/Card.java, processout-sdk/src/main/java/com/processout/processout_sdk/Contact.java
This also updates gradle build settings
=> Contact: add contact field on card tokenization

app/src/main/java/com/processout/processoutexample/MainActivity.java, processout-sdk/src/main/java/com/processout/processout_sdk/AuthorizationResult.java, processout-sdk/src/main/java/com/processout/processout_sdk/MiscGatewayRequest.java, processout-sdk/src/main/java/com/processout/processout_sdk/Network.java, processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java, processout-sdk/src/main/java/com/processout/processout_sdk/WebViewReturnAction.java
- Add support for return URL
- Improve handling of return URL
- Optimize imports
=> 3ds1: add support for 3DS1 fallback

app/build.gradle, app/src/androidTest/java/com/processout/processoutexample/ExampleInstrumentedTest.java, app/src/main/java/com/processout/processoutexample/MainActivity.java, build.gradle, gradle.properties, gradle/wrapper/gradle-wrapper.properties, processout-sdk/build.gradle, processout-sdk/src/androidTest/java/com/processout/processout_sdk/UITestSuite.java
Hello, I'd like to give a helping hand to keep this project more up to date with Android.
I noticed that it was not possible to even build the project within current version of Android Studio so I proceeded to update the Gradle wrapper to latest available version along with the Android Gradle Plugin.
The AndroidX dependencies are already used in the project, but in order to build correctly the project the `android.useAndroidX=true` flag needed to be set.
I look forward to contribute some more in the near future.
* update Gradle wrapper to version `6.8.2`.
* update Android Gradle Plugin to version `4.1.2`
* add `android.useAndroidX=true` to `gradle.properties`
* fixed failing UI tests (failing because of hardcoded card expiration date :calendar: )
The project now builds in the latest …
=> Update Gradle wrapper and Android Gradle Plugin

app/build.gradle, app/src/main/java/com/processout/processoutexample/MainActivity.java, app/src/main/res/layout/activity_main.xml, app/src/main/res/layout/content_main.xml, processout-sdk/build.gradle, processout-sdk/src/main/java/com/processout/processout_sdk/APMTokenReturn.java, processout-sdk/src/main/java/com/processout/processout_sdk/GatewayConfiguration.java, processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java, processout-sdk/src/main/java/com/processout/processout_sdk/TestActivity.java, processout-sdk/src/main/res/layout/activity_test.xml
Migrate dependencies to AndroidX.
* update all dependencies
* migrate all support dependencies to AndroidX
=> Migrate dependencies androidx

processout-sdk/src/main/java/com/processout/processout_sdk/Card.java
Updated SDK to accept Google Pay payload as part of: https://checkout.atlassian.net/browse/PROCESS0UT-495
=> allow googlepay payload to be accepted

processout-sdk/src/main/java/com/processout/processout_sdk/AuthorizationRequest.java, processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java, processout-sdk/src/main/java/com/processout/processout_sdk/TokenRequest.java
We need to add support for card verifications and incremental auth
=> PROCESS0UT-960: Add thirdPartySDKVersion on card verifications + incremental auth

processout-sdk/src/androidTest/java/com/processout/processout_sdk/UITestSuite.java, processout-sdk/src/main/java/com/processout/processout_sdk/AuthorizationRequest.java, processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java, processout-sdk/src/main/java/com/processout/processout_sdk/TokenRequest.java
https://checkout.atlassian.net/browse/POINT-261
Note: We’d like to have this same functionality on the authorization API request and not on tokenisation.
@simeon-kostadinov-cko could you add an appropriate reviewers, please
=> autorization request: preferred scheme

processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
Fixing an issue when new source is ignored during 3DS flow.
=> update source during 3DS flow

sdk/build.gradle, sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java, sdk/src/main/kotlin/com/processout/sdk/api/ProcessOutApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/NetworkConfiguration.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/interceptor/UserAgentInterceptor.kt, sdk/src/main/kotlin/com/processout/sdk/di/ContextGraph.kt, sdk/src/main/kotlin/com/processout/sdk/di/NetworkGraph.kt, sdk/src/main/kotlin/com/processout/sdk/utils/LocaleExtensions.kt, sdk/src/main/res/values/strings.xml
Added Accept-Language header.
Strings and locales refactoring to prepare for localisation.
https://checkout.atlassian.net/browse/POM-157
=> feat(POM-157): Send appropriate Accept-Language header

README.md, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodUiState.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/model/InputParameter.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/button/POButton.kt, sdk/src/main/kotlin/com/processout/sdk/utils/StringExtensions.kt, sdk/src/main/res/values/strings.xml
Local inputs validation against 3 rules (required but empty, length, type specific validations).
Error descriptions based on rule that triggered error (strings are stored locally).
Validate that phone number is in international format and starts with "+".
Pay button enabled by default, but will be disabled if user didn't correct errors from previous submission.
https://checkout.atlassian.net/browse/POM-137
=> feat(POM-137): Improve user feedback for single input validation

example/src/main/kotlin/com/processout/example/ui/shared/Default3DSHandler.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCustomerAction.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/CustomerTokensServiceImpl.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/InvoicesServiceImpl.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/ThreeDSServiceImpl.kt, sdk/src/main/kotlin/com/processout/sdk/core/POFailure.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSWebView.kt
Handle 3DS fingerprint, redirect, url.
WebView implementation.
Default 3DS test handler.
https://checkout.atlassian.net/browse/POM-171
=> feat(POM-171): Handle 3DS fingerprint, redirect, url

checkout-3ds/build.gradle, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSService.kt
Integration with Checkout build `3.0.0-testonly-10`.
https://checkout.atlassian.net/browse/POM-188
=> feat(POM-188): Update Checkout 3DS integration

sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodParameter.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/model/InputParameter.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/extensions/KeyboardExtensions.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/InputComponent.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/code/CodeInput.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/dropdown/ExposedDropdownInput.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/dropdown/ParameterValueAdapter.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/text/TextInput.kt, sdk/src/main/res/drawable/po_dropdown_icon_down.xml, sdk/src/main/res/drawable/po_dropdown_icon_states.xml, sdk/src/main/res/drawable/po_dropdown_icon_up.xml, sdk/src/main/res/layout/po_exposed_dropdown_input.xml, sdk/src/main/res/layout/po_exposed_dropdown_item.xml, sdk/src/main/res/values/dimens.xml, sdk/src/main/res/values/styles.xml
https://checkout.atlassian.net/browse/POM-193
https://user-images.githubusercontent.com/114916876/235193668-3389c9c8-3aef-4d1b-9f89-1b575db84e96.mp4
https://user-images.githubusercontent.com/114916876/235193708-6cb5ca08-89da-4515-b5d0-23f57629ed0c.mp4
https://user-images.githubusercontent.com/114916876/235193722-c1067f56-3502-4c54-9fd1-8d3245908730.mp4
=> feat(POM-193): Native APM single select dropdown component

example/build.gradle, settings.gradle
=> feat(release): 4.0.0 (fix build)

checkout-3ds/dokka/ProcessOutCheckout3DS.md, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSServiceDelegate.kt
https://checkout.atlassian.net/browse/POM-187
=> feat(POM-187): Update 3DS documentation

.github/workflows/publish.yml, build.gradle, checkout-3ds/build.gradle, example/build.gradle, jitpack.yml, scripts/publish-module.gradle, scripts/publish-root.gradle, sdk/build.gradle, settings.gradle
Includes scripts and workflow with manual trigger to build and publish artifacts to Maven Central for modules:
`sdk`
`checkout-3ds`
JitPack configuration deleted.
=> feat(POM-199): Migrate from JitPack to Maven Central

settings.gradle
=> fix(POM-199): Fix credentials to CKO repository.

.github/workflows/publish.yml
=> fix(POM-199): Fix publish workflow

.github/workflows/publish.yml, scripts/publish-module.gradle, scripts/publish-root.gradle
Added developers info required by Maven Central pom validation.
=> fix(POM-199): Added developers info

scripts/publish-module.gradle
=> fix(POM-199): Fix builds signing

README.md
https://checkout.atlassian.net/browse/POM-204
=> feat(POM-204): Update documentation after migration to Maven Central

sdk/dokka/NativeAlternativePaymentMethods.md, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt
Optional 'backPressed' cancellation of native APM bottom sheet.
https://checkout.atlassian.net/browse/POM-202
=> feat(POM-202): Optionally disable back press for native APM bottom sheet

sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt
https://checkout.atlassian.net/browse/POM-212
=> feat(POM-212): Cache native APM images in memory

sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/StyleCustomisation.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/style/dropdown/ExposedDropdownStyle.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/style/radio/PORadioButtonStateStyle.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/style/radio/PORadioButtonStyle.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/Input.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/InputComponent.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/code/CodeEditText.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/code/CodeInput.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/dropdown/ExposedDropdownInput.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/radio/RadioInput.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/text/TextInput.kt, sdk/src/main/res/color/po_radio_button_states.xml, sdk/src/main/res/drawable/po_btn_radio_material_anim.xml, sdk/src/main/res/drawable/po_btn_radio_off_mtrl.xml, sdk/src/main/res/drawable/po_btn_radio_off_to_on_mtrl_animation.xml, sdk/src/main/res/drawable/po_btn_radio_on_mtrl.xml, sdk/src/main/res/drawable/po_btn_radio_on_to_off_mtrl_animation.xml, sdk/src/main/res/layout/po_radio_input.xml, sdk/src/main/res/values/dimens.xml, sdk/src/main/res/values/styles.xml, sdk/src/main/res/values/themes.xml
Implementation adds support for radio buttons to use with single select parameters with native APMs.
Note: using current design system.
https://checkout.atlassian.net/browse/POM-213
https://github.com/processout/processout-android/assets/114916876/2af59369-65fb-40aa-aeec-f5e58f007e03
=> feat(POM-213): Support radio buttons

build.gradle, example/build.gradle, sdk/build.gradle, sdk/consumer-rules.pro
- Updated all dependencies, including Checkout 3DS SDK 3.0.2
- Added ProGuard rules to support R8 full mode
https://checkout.atlassian.net/browse/POM-217
=> feat(POM-217): Update Checkout 3DS and all dependencies

sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCardIssuerInformationResponse.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/CardsApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/CardsRepositoryImpl.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/POCardsRepository.kt, sdk/src/test/kotlin/com/processout/sdk/CardsRepositoryTests.kt
Allows to retrieve card issuer information based on iin.
https://checkout.atlassian.net/browse/POM-218
=> feat(POM-218): Allow getting card co/scheme via SDK

sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodCustomTabLauncher.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSRedirectCustomTabLauncher.kt
Temporary workaround until backend fixes Chrome redirect issue with deep links.
=> fix(ad-hoc): Force WebView in 3DS and APM Custom Tabs launchers

sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodCustomTabLauncher.kt, sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodWebViewBuilder.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSRedirectCustomTabLauncher.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSRedirectWebViewBuilder.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/POTest3DSService.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/POWebViewAuthorizationActivity.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/ProcessOutWebView.kt, sdk/src/production/kotlin/com/processout/sdk/api/network/ApiConstants.kt, sdk/src/staging/kotlin/com/processout/sdk/api/network/ApiConstants.kt
https://checkout.atlassian.net/browse/POM-224
=> feat(POM-224): Support deep links in WebView

sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodResponse.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodUiState.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt, sdk/src/main/res/layout/po_bottom_sheet_capture.xml, sdk/src/main/res/values/dimens.xml
https://checkout.atlassian.net/browse/POM-226
=> feat(POM-226): Support dynamic PSP logo for native APMs

.idea/codeStyles/Project.xml, sdk/src/main/kotlin/com/processout/sdk/api/ProcessOut.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/StyleCustomisation.kt
Also will not throw exception on subsequent invocations anymore.
Logs only for debug builds.
https://checkout.atlassian.net/browse/POM-228
=> feat(POM-228): Add 'isConfigured' property for ProcessOut

checkout-3ds/dokka/ProcessOutCheckout3DS.md, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSService.kt, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSServiceDelegate.kt, sdk/dokka/3DS.md, sdk/src/main/kotlin/com/processout/sdk/core/ProcessOutResult.kt
Additional Checkout 3DS service lifecycle callbacks.
Updated 3DS documentation.
https://checkout.atlassian.net/browse/POM-229
=> feat(POM-229): Checkout 3DS integration improvements

sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/res/layout/po_bottom_sheet_capture.xml, sdk/src/main/res/layout/po_bottom_sheet_native_apm.xml, sdk/src/main/res/values/dimens.xml
https://github.com/processout/processout-android/assets/114916876/dbea1240-5a60-4423-8fd5-31cd5df5a9cf
https://checkout.atlassian.net/browse/POM-232
=> feat(POM-232): Scrollable title section on native APM

sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodUiState.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt
Applying the following priority to dynamic logo/title:
Provider Logo -> Provider Name -> Gateway Logo
=> fix(ad-hoc): Fixed native APM dynamic logo priority

sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/input/text/TextInput.kt
Phone number formatting for TextInput of type PHONE.
https://checkout.atlassian.net/browse/POM-233
=> feat(POM-233): Phone numbers formatting

build.gradle, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/CheckoutConstants.kt, checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSService.kt, sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodCustomTabLauncher.kt
Migrated to Checkout 3DS SDK version `3.1.1`.
Added method launch(uri, returnUrl) for `POAlternativePaymentMethodCustomTabLauncher`.
https://checkout.atlassian.net/browse/POM-239
=> feat(POM-239): Update Checkout 3DS SDK integration

sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardTokenizationRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/POAllGatewayConfigurations.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/CardsRepositoryImpl.kt
https://checkout.atlassian.net/browse/POM-248
=> feat(POM-248): Expose preferred scheme when tokenizing card

checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSService.kt, example/src/main/kotlin/com/processout/example/ProcessOutExampleApplication.kt, sdk/src/main/kotlin/com/processout/sdk/api/ProcessOut.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/NetworkConfiguration.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/RemoteLoggerService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/ThreeDSServiceImpl.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/BaseLoggerService.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/LogEvent.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/POLogLevel.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/POLogger.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/POLoggerService.kt, sdk/src/main/kotlin/com/processout/sdk/core/logger/SystemLoggerService.kt, sdk/src/main/kotlin/com/processout/sdk/di/NetworkGraph.kt, sdk/src/main/kotlin/com/processout/sdk/di/ServiceGraph.kt, sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodCustomTabLauncher.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodActivityContract.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSRedirectCustomTabLauncher.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationActivityContract.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/POCustomTabAuthorizationActivity.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/POWebViewAuthorizationActivity.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/ProcessOutWebView.kt, sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/WebViewAuthorizationActivityContract.kt
Updated logging approach with better tags and message structure.
Added logs.
POLogger and it's dependencies made public with ProcessOutInternalApi annotation for logs in other modules.
https://checkout.atlassian.net/browse/POM-249
=> feat(POM-249): Add logs

sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml
Added periods to native APM error/success strings.
https://checkout.atlassian.net/browse/POM-253
=> feat(POM-253): Update native APM strings

example/src/main/res/navigation/navigation_graph.xml, example/src/main/res/values/styles.xml, example/src/main/res/values/themes.xml, sdk/src/main/kotlin/com/processout/sdk/ui/threeds/POTest3DSService.kt, sdk/src/main/res/values/config.xml, sdk/src/main/res/values/styles.xml, sdk/src/main/res/values/themes.xml, sdk/src/main/res/values/typography.xml
Migrated to Material 3 theme and tested that enabling dynamic color in host app will not affect the UI.
Added navigation animations for example app.
https://checkout.atlassian.net/browse/POM-266
=> feat(POM-266): Migrate to Material 3 theme

build.gradle, example/build.gradle, example/src/main/kotlin/com/processout/example/service/Checkout3DSServiceDelegate.kt, example/src/main/kotlin/com/processout/example/service/POAdyen3DSService.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/CardPaymentFragment.kt, example/src/main/res/layout/fragment_card_payment.xml, example/src/main/res/values/strings.xml
https://github.com/processout/processout-android/assets/114916876/9e46d1af-4787-4bbd-9fc6-ae2dc239a0a8
https://checkout.atlassian.net/browse/POM-276
=> feat(POM-276): Adyen 3DS integration example

sdk/src/main/java/com/processout/processout_sdk/CustomerActionHandler.java
Check if URI is hierarchical before attempting to retrieve a token.
https://checkout.atlassian.net/browse/POM-288
=> fix(POM-288): Handle non-hierarchical URI crash in legacy WebView

build.gradle, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt, sdk/src/main/kotlin/com/processout/sdk/ui/shared/view/extension/DisplayExtensions.kt
Fixed bottom sheet resizing based on the screen height which is now calculated in a compatible way across the APIs.
https://checkout.atlassian.net/browse/POM-295
=> fix(POM-295): Incorrect resizing of native APM bottom sheet on API 34

example/src/main/kotlin/com/processout/example/shared/ResultExtensions.kt, example/src/main/kotlin/com/processout/example/ui/screen/apm/AlternativePaymentMethodsViewModel.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/CardPaymentFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/CardPaymentViewModel.kt, example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardUpdateRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/CardsApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/CardsRepositoryImpl.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/POCardsRepository.kt, sdk/src/main/kotlin/com/processout/sdk/core/POUnit.kt, sdk/src/main/kotlin/com/processout/sdk/core/ProcessOutActivityResult.kt, sdk/src/main/kotlin/com/processout/sdk/core/ProcessOutResult.kt, sdk/src/test/kotlin/com/processout/sdk/AlternativePaymentMethodsServiceTests.kt, sdk/src/test/kotlin/com/processout/sdk/CardsRepositoryTests.kt, sdk/src/test/kotlin/com/processout/sdk/CustomerTokensRepositoryTests.kt, sdk/src/test/kotlin/com/processout/sdk/GatewayConfigurationsRepositoryTests.kt, sdk/src/test/kotlin/com/processout/sdk/InvoicesRepositoryTests.kt, sdk/src/test/kotlin/com/processout/sdk/config/TestExtensions.kt
New `updateCard()` API method with better signature.
Method `updateCVC()` is deprecated.
Helper extension functions for `ProcessOutResult` and `ProcessOutActivityResult` to simplify result handling.
Updated tests and documentation.
https://checkout.atlassian.net/browse/POM-303
=> feat(POM-303): Improve card update API

example/src/main/kotlin/com/processout/example/ui/screen/features/FeaturesFragment.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POActionsContainer.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/PODragHandle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POHeader.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POText.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/state/POActionState.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/state/POFieldState.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/state/POImmutableCollection.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POActionsContainerStyle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POAxis.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POBackgroundStyle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/theme/Dimensions.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/POCardUpdateConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/configuration/POCancellationConfiguration.kt
Actions container & Header.
Screen configuration and styles.
Cancellation logic.
https://checkout.atlassian.net/browse/POM-304
=> feat(POM-304): Card Update Screen (Layout & Configuration)

README.md, example/src/main/res/layout/fragment_features.xml
* Updated README.md
* Reordered features in example app
=> feat(ad-hoc): Updated README.md

.idea/codeStyles/Project.xml, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/Dimensions.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/Ime.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/Screen.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/extension/DimensionExtensions.kt
Screen resizes correctly basing on keyboard visibility and available space.
[small_screen.webm](https://github.com/processout/processout-android/assets/114916876/06818188-09c4-4214-86ec-6b5a70faffb0)
https://checkout.atlassian.net/browse/POM-313
=> feat(POM-313): Adapt card update for small screens

sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt
Retry requests on 408 Request Timeout.
https://checkout.atlassian.net/browse/POM-315
https://checkout.atlassian.net/browse/POS-792
=> feat(POM-315): Retry requests on 408

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/POLabeledTextField.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/POTextField.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/state/POFieldState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/Focus.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/Lifecycle.kt
* Restore field focus in onResume lifecycle event.
* Use `TextFieldValue` to handle cursor and selection.
https://checkout.atlassian.net/browse/POM-316
=> feat(POM-316): (Card Update) Restore focus and cursor on resume

sdk/src/main/kotlin/com/processout/sdk/api/ProcessOut.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/DefaultEventDispatchers.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/PONativeAlternativePaymentMethodEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/nativeapm/DefaultNativeAlternativePaymentMethodEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/DeviceData.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/ApiFailureMapper.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCardsRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCustomerTokensRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultGatewayConfigurationsRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultLogsRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultAlternativePaymentMethodsService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultBrowserCapabilitiesService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultCustomerTokensService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultInvoicesService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultThreeDSService.kt, sdk/src/main/kotlin/com/processout/sdk/di/ContextGraph.kt, sdk/src/main/kotlin/com/processout/sdk/di/NetworkGraph.kt, sdk/src/main/kotlin/com/processout/sdk/di/RepositoryGraph.kt, sdk/src/main/kotlin/com/processout/sdk/di/ServiceGraph.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
* Lazy initialization of SDK services and components.
* Inject ApiFailureMapper to all repositories instead of Moshi directly.
* Improved implementation of ApiFailureMapper.
* Fixed screen size calculation for device metadata.
* Added `'channel' = 'android'` to device metadata.
* Refactored PONativeAlternativePaymentMethodEventDispatcher from abstract class to interface.
* `*Impl` renamed to `Default*` everywhere.
* Various small code improvements.
=> fix(ad-hoc): Internal code improvements

ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt
Optimized buttons and fields recompositions.
Simplified handling of completion and screen mode.
=> fix(ad-hoc): Card Update optimizations

sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/card/update/POCardUpdateEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/card/update/PODefaultCardUpdateEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardUpdateShouldContinueRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCardUpdateShouldContinueResponse.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodDefaultValuesResponse.kt, sdk/src/main/kotlin/com/processout/sdk/core/annotation/ProcessOutInternalApi.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/annotation/ProcessOutInternalApi.kt, ui/documentation/ProcessOutUI.md, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt
Error handling mechanism for Card Update screen via `POCardUpdateEventDispatcher`.
Allows to decide whether the flow should continue or complete after the failure.
https://checkout.atlassian.net/browse/POM-330
=> feat(POM-330): (Card Update) Error handling

example/src/main/kotlin/com/processout/example/ui/screen/card/tokenization/CardTokenizationFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/tokenization/CardTokenizationViewModel.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POButton.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POCircularProgressIndicator.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/PODragHandle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POText.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/POTextField.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationActivityContract.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationData.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationFormData.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationLauncher.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/composable/ExpandableText.kt
Changes applied to both Card Tokenization & Card Update screens:
* Submit, validation and buttons state depends on invalid fields instead of error message.
* Focus on first invalid field.
* Disable submit from keyboard while already submitting.
* Use required components sizes instead of preferred.
Card Update:
* Fixed fields spacing.
* Expandable error message.
Card Tokenization:
* Optional section title.
* Submit, validation and error state.
* Ability to restore form data and error state.
https://checkout.atlassian.net/browse/POM-335
=> feat(POM-335): (Card Tokenization & Update) Submit and validation

build.gradle, sdk/build.gradle, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardTokenizationRequest.kt, sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, ui/build.gradle, ui/src/main/assets/AddressSpecifications.json, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationFormData.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/extension/LocaleExtensions.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/address/AddressSpecification.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/address/AddressSpecificationAdapter.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/address/AddressSpecificationProvider.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/address/AddressSpecificationStringRes.kt
Billing address section implementation.
Address specification.
Localizations.
[billing_address.webm](https://github.com/processout/processout-android/assets/114916876/6529ab8e-57f7-476e-bf85-8aba9dd6df4b)
https://checkout.atlassian.net/browse/POM-334
=> feat(POM-334): (Card Tokenization) Billing address

example/src/main/kotlin/com/processout/example/service/googlepay/GooglePayConfiguration.kt
Extended GooglePayConfiguration in example app to full specification.
=> chore: Extended GooglePayConfiguration in example app

build.gradle, sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/POCustomTabAuthorizationActivity.kt
=> feat(ad-hoc): Updated dependencies

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt
=> fix(ad-hoc): Code field improvements

sdk/src/main/kotlin/com/processout/sdk/core/retry/RetryStrategy.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt
* Capture polling with exponential retry strategy.
* Max capture timeout increased to 15 minutes, by default 3 minutes.
https://checkout.atlassian.net/browse/POM-367
=> feat(POM-367): (Native APM) Capture polling strategy

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POActionsContainer.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POHeader.kt, ui/src/main/kotlin/com/processout/sdk/ui/base/BaseBottomSheetDialogFragment.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModelState.kt
* Layouts, animations and resizing for the whole flow.
* Interactor and VM states structure.
[napm_flow.webm](https://github.com/processout/processout-android/assets/114916876/ab775d84-1d9c-4fd1-a736-8d14f61a0e40)
https://checkout.atlassian.net/browse/POM-369
=> feat(POM-369): Migrate native APM to Compose (part 2)

example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmUiState.kt, example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmViewModel.kt, example/src/main/res/values/strings.xml, sdk/documentation/NativeAlternativePaymentMethods.md, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POActionsContainer.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POButton.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/dropdown/PODropdownField.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/radio/PORadioGroup.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/text/POTextField.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/theme/Dimensions.kt, ui/documentation/NativeAlternativePaymentMethods.md, ui/documentation/ProcessOutUI.md, ui/src/main/kotlin/com/processout/sdk/ui/base/BaseBottomSheetDialogFragment.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentLauncher.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/component/TextAndroidView.kt
* Adaptive screen height
* UI improvements
* Implementation made public
* Updated documentation
* Updated example app
https://checkout.atlassian.net/browse/POM-369
=> feat(POM-369): Migrate native APM to Compose (finalization)

sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt, sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
=> feat(ad-hoc): Updated localizations

sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultAlternativePaymentMethodsService.kt, sdk/src/testProductionDebug/kotlin/com/processout/sdk/AlternativePaymentMethodsServiceTests.kt
Adds an ability to generate URL that can be used to authorize invoice with previously tokenized APM.
=> feat(ad-hoc): Tokenized APM URL

sdk/src/main/kotlin/com/processout/sdk/api/model/event/PONativeAlternativePaymentMethodEvent.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt
Following events now include parameters metadata and values:
`ParametersChanged`
`WillSubmitParameters`
https://checkout.atlassian.net/browse/POM-386
=> feat(POM-386): Extend native APM events

sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultCustomerTokensService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultInvoicesService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultThreeDSService.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
* Refined log levels
* Added more logs
=> feat(ad-hoc): Refine log levels

example/src/main/kotlin/com/processout/example/ui/screen/checkout/DefaultDynamicCheckoutDelegate.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutUiState.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/InvoicesApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt
* Added 'clientSecret' to POInvoice
* Updated fetching and creating of invoice
=> feat(ad-hoc): Add 'clientSecret' to POInvoice

example/src/main/kotlin/com/processout/example/ui/screen/card/payment/CardPaymentFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/payment/CardPaymentUiState.kt, example/src/main/kotlin/com/processout/example/ui/screen/card/payment/CardPaymentViewModel.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DefaultDynamicCheckoutDelegate.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutUiState.kt, example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutViewModel.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/card/tokenization/POCardTokenizationEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/card/tokenization/PODefaultCardTokenizationEventDispatcher.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardTokenizationProcessingRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POInvoiceAuthorizationRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodParameter.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/InvoicesApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt, sdk/src/main/res/values/strings.xml, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POText.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/checkbox/POCheckbox.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/radio/PORadioGroup.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POCheckboxStyle.kt, ui/documentation/CardTokenization.md, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModelState.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/CardTokenization.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
* Added checkbox component
* Card saving implementation for Card Tokenization and Dynamic Checkout
* `processTokenizedCard` is deprecated in `POCardTokenizationEventDispatcher`, instead introduced `processTokenizedCardRequest` which includes `saveCard` in `POCardTokenizationProcessingRequest`
* `savingAllowed` in `POCardTokenizationConfiguration` marked as internal until localization is ready
* UI fixes
* Updated example app to support card saving
* Updated documentation
https://github.com/user-attachments/assets/3b57b428-0d3e-4cf3-9432-93c6e58cce57
https://checkout.atlassian.net/browse/POM-404
=> feat(POM-404): Support saving card on Card Tokenization and Dynamic Checkout

sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt, sdk/src/main/kotlin/com/processout/sdk/core/coroutines/POCloseableCoroutineScope.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POButton.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POText.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POBrandButtonStyle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POButtonDefaults.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POButtonStyle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POColor.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/theme/Colors.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/theme/ProcessOutTheme.kt, ui/src/main/kotlin/com/processout/sdk/ui/base/BaseInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModelState.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/extension/ColorExtensions.kt
* Processing Dynamic Checkout express payments (all types except of Google Pay)
* Branded express payment button and styles
* Related refactoring
https://github.com/user-attachments/assets/1749912f-e6e0-4928-9222-e71872aa9244
https://checkout.atlassian.net/browse/POM-401
https://checkout.atlassian.net/browse/POM-403
=> feat(POM-401): Dynamic Checkout express payments

build.gradle, sdk/build.gradle, sdk/src/main/kotlin/com/processout/sdk/api/service/googlepay/PODefaultGooglePayService.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/googlepay/POGooglePayConfiguration.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/googlepay/POGooglePayRequestBuilder.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/googlepay/POGooglePayService.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POGooglePayButtonStyle.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/theme/ProcessOutTheme.kt, ui/build.gradle, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutEvent.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModelState.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/googlepay/POGooglePayCardTokenizationLauncher.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/component/GooglePayButton.kt
https://github.com/user-attachments/assets/02b530fa-5f4d-4644-b864-d2979f3d55fb
https://checkout.atlassian.net/browse/POM-417
=> feat(POM-417): Google Pay on Dynamic Checkout

sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
Enables card saving feature on Card Tokenization.
Added localizations.
Sending missing `DidComplete` event.
=> feat(ad-hoc): Enable card saving feature

build.gradle, sdk/src/main/kotlin/com/processout/sdk/api/model/request/PODynamicCheckoutInvoiceAuthorizationRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/PODynamicCheckoutInvoiceAuthorizationResponse.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutDelegate.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
Allow to alter invoice authorization request on Dynamic Checkout via delegate.
https://checkout.atlassian.net/browse/POM-425
=> feat(POM-425): Allow to alter authorization request on Dynamic Checkout

sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
Mapping Google Pay `countryCode` from backend configuration.
https://checkout.atlassian.net/browse/POM-421
=> feat(POM-421): Google Pay country code

.idea/kotlinc.xml, build.gradle
CKO 3DS SDK `3.2.4`
Compose `2024.10.01`
Kotlin `2.0.21`
Android and other libs
=> feat(ad-hoc): Update dependencies

README.md
=> fix(ad-hoc): Updated README.md

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt
Calculates if code field will fit into available row width and decreases each code item width if not.
Improvement: recalculates values and focus when length is changed.
https://checkout.atlassian.net/browse/POM-439
=> feat(POM-439): (DC) Fit code field on small screens

sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/shared/configuration/POBarcodeConfiguration.kt
* Barcode localizations.
* Removed `@ProcessOutInternalApi` annotation from `POBarcodeConfiguration` and nAPM (Compose) configuration property.
=> feat(ad-hoc): Barcode localizations

ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
Optionally preselect single regular payment method (only if there is no express methods).
https://checkout.atlassian.net/browse/POM-440
=> feat(POM-440): (DC) Optionally pre-select single regular payment method

sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardUpdateRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCardsRepository.kt, sdk/src/testProductionDebug/kotlin/com/processout/sdk/CardsRepositoryTests.kt
Added `preferredScheme` to `POCardUpdateRequest`.
https://checkout.atlassian.net/browse/POM-322
=> feat(POM-322): Support preferred scheme update

.github/workflows/release-documentation.yml
=> fix(ad-hoc): Fix release documentation workflow

ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
Fixes the bug causing billing address fields to be cleared when implementation requests to process tokenized card.
=> fix(ad-hoc): Card Tokenization billing address

sdk/src/main/kotlin/com/processout/sdk/api/model/request/PODynamicCheckoutInvoiceInvalidationReason.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/response/POTransaction.kt, sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutDelegate.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt
* Dynamic Checkout code documentation.
* Updated delegate interface to not expose dispatcher requests.
* Separate `CancelButton` for `AlternativePaymentConfiguration`.
* nAPM configuration
* Added annotation IntRange 0-900 seconds for payment confirmation timeout.
* Removed internal range validation.
* Updated interactor logic condition of `capturePassedTimestamp` from `<` to `<=` to make at least single capture call if timeout set to 0.
https://checkout.atlassian.net/browse/POM-432
=> feat(POM-432): Dynamic Checkout code documentation

sdk/src/main/kotlin/com/processout/sdk/core/POFailure.kt
Removed error code `request.validation.invalid-invoice` that was added in previous PR as it won't be added on the backend.
=> fix(ad-hoc): Remove error code

sdk/src/main/kotlin/com/processout/sdk/api/network/interceptor/UserAgentInterceptor.kt
Added header `Accept: */*` to all requests.
=> feat(ad-hoc): Add Accept header to all requests

.github/workflows/create-release-and-publish.yml, .github/workflows/create-release-candidate.yml, .github/workflows/github-conventions.yaml, .github/workflows/run-tests.yml
=> fix(ad-hoc): Add workflows permission

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt
* Added text support in `POCodeField`.
* Reimplemented next field focus logic.
* Max supported length changed to `8`.
https://github.com/user-attachments/assets/b02496cd-7518-4f41-b938-74ea0bceeb3d
https://checkout.atlassian.net/browse/POM-494
=> feat(POM-494): Support text OTP UI component

sdk/src/main/kotlin/com/processout/sdk/api/model/response/napm/v2/PONativeAlternativePaymentNextStep.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/LabeledFieldLayout.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/checkbox/POCheckbox.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/checkbox/POLabeledCheckboxField.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentViewModelState.kt
https://github.com/user-attachments/assets/860e0b0e-6a03-49c6-af71-5c772e047b9e
https://checkout.atlassian.net/browse/POM-505
=> feat(POM-505): Add checkbox for boolean parameter

sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentViewModelState.kt, ui/src/main/res/drawable-night/po_success_image_v2.xml, ui/src/main/res/drawable/po_success_image_v2.xml
Success screen, `displayDuration` logic and styling.
https://github.com/user-attachments/assets/5e995ca6-8f70-4542-982d-4f9c85ad96de
https://checkout.atlassian.net/browse/POM-510
=> feat(POM-510): Success screen

example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmFragment.kt, example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmUiState.kt, example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmViewModel.kt, example/src/main/res/layout/fragment_native_apm.xml, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCreateCustomerRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCreateInvoiceRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/napm/v2/NativeAlternativePaymentRequestBody.kt, sdk/src/main/kotlin/com/processout/sdk/api/model/request/napm/v2/PONativeAlternativePaymentAuthorizationRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCustomerTokensRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt, sdk/src/main/res/values-ar/strings.xml, sdk/src/main/res/values-fr/strings.xml, sdk/src/main/res/values-pl/strings.xml, sdk/src/main/res/values-pt/strings.xml, sdk/src/main/res/values/strings.xml, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentEvent.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/napm/delegate/v2/PONativeAlternativePaymentEvent.kt
* Support for web redirects
* Authorize with customer token
* Fields validation by length
* Updated `PONativeAlternativePaymentEvent` (including `DidFail` with `paymentState`)
* Updated localizations
* Removed replacement to local error messages
* Updated example app
https://github.com/user-attachments/assets/874693db-314a-4b38-90be-73accdc8e0b4
https://checkout.atlassian.net/browse/POM-497
https://checkout.atlassian.net/browse/POM-515
https://checkout.atlassian.net/browse/POM-511
=> feat(POM-497): nAPM v2 web redirect and improvements

.github/workflows/create-release-and-publish.yml, scripts/publish-root.gradle
Updated Maven publishing script and workflow.
Note: Actions secrets updated as well.
=> fix(ad-hoc): Update Maven publishing script and workflow

build.gradle, sdk/src/main/kotlin/com/processout/sdk/api/model/request/POInvoiceRequest.kt, sdk/src/main/kotlin/com/processout/sdk/api/network/InvoicesApi.kt, sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt, sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultInvoicesService.kt, ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt, ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsInteractor.kt
* Optionally expand payment methods when retrieving invoice.
* Added compiler argument `-Xconsistent-data-class-copy-visibility` for all modules.
=> feat(ad-hoc): Expand invoice payment methods

README.md
Added Netcetera 3DS module to README.md
=> feat(ad-hoc): Update README.md

ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POButton.kt, ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/PODialog.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/screen/CardTokenizationContent.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/screen/CardTokenizationScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt, ui/src/main/kotlin/com/processout/sdk/ui/card/update/POCardUpdateConfiguration.kt
Updated design system on the following screens:
`POCardTokenization`
`POCardScanner`
`POCardUpdate`
=> feat(ad-hoc): Update design system on the card screens
