processout/processout-android

- processout-sdk/src/main/java/com/processout/processout_sdk/Network.java
Volley was already sending the correct content-type header.
Specifying the same header ended up duplicating them in the request.
> network: fix header issue where content-type was duplicated

- app/src/main/java/com/processout/processoutexample/MainActivity.java
- processout-sdk/src/androidTest/java/com/processout/processout_sdk/ProcessOutTest.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
Previously the context used to start a new activity was passed during the `ProcessOut` object instantiation. 
This context was used to handle the networking queue, to instantiate a new Activity when a Web redirection was needed and also to display a hidden webview when performing a web fingerprinting.
This caused some issues when dealing with Dependency Injection as the context wasn't an `Activity` but rather an `ApplicationContext` with which we can't be adding views directly.
The solution is to follow the same flow as the iOS SDK by passing the current Activity context to the `makeCardPayment` method. We however still keep the `ApplicationContext` passed during the SDK instantiation as we will use this one to handle the networking.
> SDK: Change context parameters to support DI setups

- app/src/main/java/com/processout/processoutexample/MainActivity.java
- processout-sdk/src/main/java/com/processout/processout_sdk/AlternativeGateway.java
- processout-sdk/src/main/java/com/processout/processout_sdk/CustomerAction.java
- processout-sdk/src/main/java/com/processout/processout_sdk/CustomerActionHandler.java
- processout-sdk/src/main/java/com/processout/processout_sdk/CvcUpdateCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ListAlternativeMethodsCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/Network.java
- processout-sdk/src/main/java/com/processout/processout_sdk/POWebViews/CardTokenWebView.java
- processout-sdk/src/main/java/com/processout/processout_sdk/POWebViews/PaymentWebView.java
- processout-sdk/src/main/java/com/processout/processout_sdk/POWebViews/ProcessOutWebView.java
- processout-sdk/src/main/java/com/processout/processout_sdk/POWebViews/WebViewCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOutExceptions/ProcessOutAuthException.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOutExceptions/ProcessOutCardException.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOutExceptions/ProcessOutWebException.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ThreeDSHandler.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ThreeDSVerificationCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/TokenRequest.java
The `makeCardToken` is now available:
```java
p.makeCardToken("card-token", "customer-id", "token-id", ProcessOut.createDefaultTestHandler(MainActivity.this, new ProcessOut.ThreeDSHandlerTestCallback() {
@Override
public void onSuccess(String tokenId) {
// The card has been verified
}
@Override
public void onError(Exception error) {
// Error
}
}), with);
```
The `ThreeDSHandler` interface has a new method:
```java
void doPresentWebView(ProcessOutWebView webView);
```
It is called when a web challenge is required. It is up to you to present the webview the way you want.
The only case where your app will be re-opened from a deep-link is when dealing with Alternative Payment Methods.
The `onCreate` method of your Activity should handle it like this:
```java
@Override
protected void …
```
> Add support for makeCardToken method + WebViews challenges

- processout-sdk/src/androidTest/java/com/processout/processout_sdk/ProcessOutTest.java
- processout-sdk/src/androidTest/java/com/processout/processout_sdk/UITestSuite.java
- processout-sdk/src/main/java/com/processout/processout_sdk/APMTokenReturn.java
- processout-sdk/src/main/java/com/processout/processout_sdk/FetchGatewaysConfigurationsCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/GatewayConfiguration.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ListAlternativeMethodsCallback.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
It is now possible to create an APM token for customer token.
Refer to the [documentation to create a customer token](https://docs.processout.com/payments/save-token-and-capture-later/#step-2:-create-a-customer-token) **with an empty source**.
Also, during the token creation call, specify a `return_url` with your app scheme and `processout.return` as host.
Ex: `yourapp://processout.return`
This will allow your user to re-open the app once the APM verification is completed.
First list your available APM gateways:
```java
p.fetchGatewayConfigurations(ProcessOut.GatewaysListingFilter.AlternativePaymentMethodWithTokenization, new FetchGatewaysConfigurationsCallback() {
@Override
public void onSuccess(ArrayList<GatewayConfiguration> gateways) {
p.makeAPMToken(gateways.get(0), "customer-id", …
```
> Apm: add support for makeAPMToken method

- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
Fix an issue where tokenizing or requesting a payment through an APM with the application context would cause a crash.
This adds a new parameter for `makeAPMToken` and `makeAPMPayment` to pass the Activity context instead (same behavior as for cards).
> context: add new parameter to use pass activity context for APMs

- processout-sdk/src/main/java/com/processout/processout_sdk/Gateway.java
- processout-sdk/src/main/java/com/processout/processout_sdk/GatewayConfiguration.java
This allows merchants to reconstruct gateways list when re-opening the app without re-fetching them.
> Gateways: add public constructor to gateway objects

- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
Previously, when initiating a payment via APM, the redirection was done by the PO SDK.
This changes the flow by returning the URL so that merchants can display the page within a webview.
(Same changes have been made to iOS SDK)
> APMs: directly returns the redirection URL

- processout-sdk/src/main/java/com/processout/processout_sdk/Card.java
Added ability to pass in contact details and Card holder name when tokenizing a Google Pay payload.
> add contact and cardholder name to payload for Google Pay

- processout-sdk/src/main/java/com/processout/processout_sdk/AuthorizationRequest.java
- processout-sdk/src/main/java/com/processout/processout_sdk/DirectoryServerData.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
The scheme and the issuer can decide of the protocol of the version during an authentication to offer more features, like exemptions, delegated authentication (rely on a 3rd party to do the authentication) or decoupled authentication (authentication that isn’t in the 3DS flow, eg offline).
When doing an authentication, the payment provider will indicate us on what version should we authenticate.
As of now, we force our merchants to use a static value of 2.1.
Overload makeCardPayment method to accept and forward the SDKVersion and also modify the DirectoryServerData class to be able to unmarshal the messageVersion and access it.
Version of tessel9 needs to be update, don't mind the go-mod changes, used custom version of t9 to test this. 
This change requires a few other changes in these …
> add message and SDK version support for 3ds2 auth

- processout-sdk/src/main/java/com/processout/processout_sdk/CustomerActionHandler.java
Fix possible `ClassCastException` in case if `with` parameter is not an instance of `Activtiy`.
Moved the casting right to the place where it's used and make it inside the "instanceof" check.
> Fix ClassCastException from Context to Activity in CustomerActionHandler.java

- processout-sdk/src/main/java/com/processout/processout_sdk/Network.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
We are trying to unmarshal an unexpected response in some cases and it's causing a crash since it's not properly handled. 
Related to: https://github.com/processout/processout-android/issues/36
> properly handle invalid response in network call

- processout-sdk/src/main/java/com/processout/processout_sdk/CustomerActionHandler.java
- processout-sdk/src/main/java/com/processout/processout_sdk/ProcessOut.java
Fixing an issue when trying to verify a card and stuck on “You’ll be redirected soon to the merchant” screen rather than being redirect back to the main screen. This happens when handling fingerprint customer action.
> Fix redirect to merchant during fingerprint customer action handling

- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt
`BottomSheetBehavior.BottomSheetCallback` is now added in `onResume()` and removed in `onPause()`.
Previously was added in `onShow()` and never removed.
This should ensure that `binding` is non-null when callback is triggered, but I couldn't reproduce the issue, so added null checks just in case, anyway callback code shouldn't be executed in state when binding is null.
https://checkout.atlassian.net/browse/POM-240
> feat(POM-240): Fixed binding NPE in BottomSheetBehavior.BottomSheetCallback

- .github/workflows/create-release-and-publish.yml
- build.gradle
- sdk/build.gradle
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationUiState.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationViewModel.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/POCustomTabAuthorizationActivity.kt
Fixed redirection loop when Activity and ViewModel is destroyed by saving ViewModel state in SavedStateHandle.
Fixed cancellation.
Handle case when deep link is received after flow is finished (consecutive redirection from Chrome browser instead of Custom Tab).
Tested with `Don't keep activities` developer option.
Related issue: https://github.com/processout/processout-android/issues/111
https://checkout.atlassian.net/browse/POM-256
> feat(POM-256): Handle Custom Tab activity destruction

- sdk/src/main/kotlin/com/processout/sdk/api/model/request/POAllGatewayConfigurationsRequest.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardTokenizationRequest.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POAlternativePaymentMethodResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCustomerAction.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCustomerTokenResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodParameter.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodState.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/threeds/PO3DS2Configuration.kt
Annotated all request/response enums with `@JsonClass(generateAdapter = false)` to prevent them from being removed/obfuscated by R8/ProGuard.
It's required by Moshi when obfuscation is enabled:
https://github.com/square/moshi#enums
https://checkout.atlassian.net/browse/POM-260
> feat(POM-260): Prevent enums from being removed/obfuscated by R8/ProGuard

- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt
Properly canceles animations when user leaves the screen during animation.
This prevents binding NPE crash and allows to restore the state correctly when user goes back to the screen.
https://checkout.atlassian.net/browse/POM-268
> fix(POM-268): Native APM binding NPE in animation callback

- sdk/src/main/kotlin/com/processout/sdk/api/service/CustomerTokensServiceImpl.kt
- sdk/src/main/kotlin/com/processout/sdk/api/service/InvoicesServiceImpl.kt
Added `cleanup()` calls to provided 3DS service implementation in `InvoicesServiceImpl.authorizeInvoice()` and `CustomerTokensServiceImpl.assignCustomerToken()` to handle the following cases:
1) Failure happened in internal 3DS service (e.g. exception in `try-catch`). It can happen on any stage of the flow, but it's a terminal failure so resources of provided 3DS service must be cleaned.
2) Failure happened in delegated 3DS implementation which callbacks to internal service. In this case it will simplify the cleanup logic for the implementation as it will be centralized. Service still can have a custom cleanup logic for special cases if required and it's up to implementation to make sure that service is able to handle `cleanup()` when it's called. `POCheckout3DSService` already follows …
> fix(POM-278): Cleanup 3DS implementation on failures

- sdk/src/main/res/drawable/po_drag_handle.xml
Lighter drag handle color on native APM bottom sheet to match with Card Update.
> fix(ad-hoc): Lighter drag handle color on native APM

- sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultAlternativePaymentMethodsService.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/apm/POAlternativePaymentMethodCustomTabLauncher.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/threeds/PO3DSRedirectCustomTabLauncher.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/threeds/ThreeDSRedirectWebAuthorizationDelegate.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationUiState.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationViewModel.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabConfiguration.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/POCustomTabAuthorizationActivity.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/ProcessOutWebView.kt
- sdk/src/test/kotlin/com/processout/sdk/AlternativePaymentMethodsServiceTests.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationFormData.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationResponse.kt
1) `token` query parameter in deep link return URI is now optional for 3DS and web APM flows.
2) Custom Chrome Tab return URI is validated against value that was provided to launcher.
3) Small improvements in ProcessOutWebView.
Public card tokenization classes marked as internal because they are WIP.
https://checkout.atlassian.net/browse/POM-327
> feat(POM-327): Token is optional when parsing 3DS and APM return deep link

- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodActivityContract.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationActivityContract.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/webview/WebViewAuthorizationActivityContract.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationActivityContract.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateActivityContract.kt
In low memory condition Android can persist activity result and parse it in its own process using framework class loader, which cannot load classes from SDK.
```
Fatal Exception: android.os.BadParcelableException: ClassNotFoundException when unmarshalling: com.processout.sdk.core.ProcessOutActivityResult$Success
```
`setExtrasClassLoader()` when parsing result in all activity contracts.
https://checkout.atlassian.net/browse/POM-331
> fix(POM-331): Crash while parsing result in activity contract

- build.gradle
Crash happens during app update on Android 33+ when using CKO 3DS SDK.
```
Fatal Exception: java.lang.RuntimeException: Unable to start receiver com.checkout.threeds.sec.PackageUpdateBroadcastReceiver: java.security.GeneralSecurityException: Keystore key generation failed
```
Checkout 3DS SDK updated to version `3.2.1` which includes fix for this issue.
> fix(ad-hoc): Checkout 3DS SDK crash (PackageUpdateBroadcastReceiver)

- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodUiState.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/StyleCustomization.kt
- sdk/src/main/res/layout/po_bottom_sheet_capture.xml
Added native APM configuration property `showPaymentConfirmationProgressIndicatorAfterSeconds` to show the progress indicator during payment confirmation after provided delay.
Recording shows how progress indicator appears after 3 seconds with a custom color and transition background/foreground, following to the success screen.
[napm_loader.webm](https://github.com/processout/processout-android/assets/114916876/d4773014-b86f-49de-85be-79c8703110a4)
https://checkout.atlassian.net/browse/POM-351
> feat(POM-351): (Native APM) Optional loader by timeout on capture screen

- ui-core/build.gradle
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/PORequestFocus.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/LabeledFieldLayout.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POLabeledCodeField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/texttoolbar/FloatingTextActionModeCallback.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/texttoolbar/PrimaryTextActionModeCallback.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/texttoolbar/ProcessOutTextToolbar.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/texttoolbar/TextActionModeCallback.kt
- ui/build.gradle
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt
`POCodeField` and `POLabeledCodeField` with custom `ProcessOutTextToolbar` that allows to `Paste` and disable other actions. `PORequestFocus` and its `lifecycle` dependency moved to `ui-core` module.
[code_field_compose.webm](https://github.com/processout/processout-android/assets/114916876/23e6d647-055c-42fc-869e-26a31a376e78)
https://checkout.atlassian.net/browse/POM-359
> feat(POM-359): Code field in Compose

- ui/src/main/kotlin/com/processout/sdk/ui/googlepay/GooglePayService.kt
Google Pay API throws an exception when checking readiness on the device where it's not available:
`com.google.android.gms.common.api.ApiException: 17: API: Wallet.API is not available on this device. Connection failed with: ConnectionResult{statusCode=SERVICE_INVALID, resolution=null, message=null}`
Catching and logging.
> fix(ad-hoc): Catch Google Pay API exception

- sdk/src/main/kotlin/com/processout/sdk/api/model/response/NativeAlternativePaymentMethodResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodParameterValues.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodState.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodTransactionDetails.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
1) Restore native APM state when screen is re-launched during transaction.
2) Added new `FAILED` state.
3) Added retries for the following status codes:
- 409 Conflict
- 425 Too Early
- 429 Too Many Requests
https://checkout.atlassian.net/browse/POM-363
> feat(POM-363): Restore native APM state

- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmFragment.kt
- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmUiState.kt
- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmViewModel.kt
- example/src/main/res/layout/fragment_native_apm.xml
- example/src/main/res/values/strings.xml
- sdk/src/main/kotlin/com/processout/sdk/api/ProcessOut.kt
- sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/DefaultEventDispatchers.kt
- sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/POEventDispatchers.kt
- sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/PONativeAlternativePaymentMethodEventDispatcher.kt
- sdk/src/main/kotlin/com/processout/sdk/api/dispatcher/napm/PODefaultNativeAlternativePaymentMethodEventDispatcher.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/core/POUnit.kt
- sdk/src/main/kotlin/com/processout/sdk/core/retry/PORetryStrategy.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/POFieldLabels.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/code/POCodeField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/style/POBackgroundStyle.kt
- ui/src/main/AndroidManifest.xml
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentActivityContract.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentLauncher.kt
Foundation
https://checkout.atlassian.net/browse/POM-369
> feat(POM-369): Migrate native APM to Compose (part 1)

- build.gradle
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POColor.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/web/customtab/CustomTabAuthorizationViewModel.kt
- sdk/src/main/res/values-ar/strings.xml
- sdk/src/main/res/values-fr/strings.xml
- sdk/src/main/res/values-pl/strings.xml
- sdk/src/main/res/values-pt/strings.xml
- sdk/src/main/res/values/strings.xml
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
* ViewModel, Interactor, states, events, data flow.
* Ability to reset and reuse ViewModels and Interactors of CardTokenization and NativeAlternativePayment.
* Updated localizations.
https://checkout.atlassian.net/browse/POM-387
> feat(POM-387): Dynamic Checkout ViewModel & Interactor

- build.gradle
Checkout 3DS SDK **3.2.3** uses latest DexProtector which fixes startup crash on some devices:
```
Exception java.lang.RuntimeException: Unable to get provider com.checkout.threeds.LibContentProvider: java.lang.RuntimeException: DP: 714
```
> fix(ad-hoc): Checkout 3DS SDK 3.2.3

- sdk/src/main/kotlin/com/processout/sdk/api/preferences/Preferences.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCardsRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultCustomerTokensRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultGatewayConfigurationsRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultInvoicesRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/DefaultTelemetryRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/api/service/TelemetryService.kt
- sdk/src/main/kotlin/com/processout/sdk/api/service/proxy3ds/PODefaultProxy3DSService.kt
- sdk/src/main/kotlin/com/processout/sdk/core/coroutine/POCloseableCoroutineScope.kt
- sdk/src/main/kotlin/com/processout/sdk/di/ContextGraph.kt
- sdk/src/main/kotlin/com/processout/sdk/di/RepositoryGraph.kt
- sdk/src/main/kotlin/com/processout/sdk/di/ServiceGraph.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/googlepay/POGooglePayCardTokenizationLauncher.kt
Refactored usages of coroutine scopes to apply the following rules:
1) Created `mainScope` in `ContextGraph`. It used in all services and repositories whose scope should be active throughout the whole SDK/app lifetime. It never cancels.
2) `Dispatchers.Main.immediate` used only in components responsible to update the UI (activity/VM/interactor) and bound to component lifecycle.
3) Short lived components (like `PODefaultProxy3DSService`) have it's own `MainScope()` which is cancelled when component is not needed anymore.
4) Other components will use the scope of parent component whenever possible (e.g. launchers use `lifecycleScope`).
> fix(ad-hoc): Refactor coroutine scopes

- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
Standalone Compose implementations of nAPM and Card Tokenization are started explicitly in `onAttach()` method of their respective `BottomSheetDialogFragment`.
`onAttach()` method is called again on Android configuration changes (e.g. dark/light theme, language, etc...) causing `viewModel.start()` to be called again as well, leading to inconsistent state and sending of redundant lifecycle events.
This PR prevents subsequential starts when flow is already started.
> fix(ad-hoc): Prevent starting of nAPM and Card Tokenization on Android configuration changes

- example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutFragment.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/event/PONativeAlternativePaymentMethodEvent.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodUiState.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodBottomSheet.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/PONativeAlternativePaymentMethodConfiguration.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/StyleCustomization.kt
- sdk/src/main/res/layout/po_bottom_sheet_capture.xml
- sdk/src/main/res/values-ar/strings.xml
- sdk/src/main/res/values-fr/strings.xml
- sdk/src/main/res/values-pl/strings.xml
- sdk/src/main/res/values-pt/strings.xml
- sdk/src/main/res/values/strings.xml
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/NativeAlternativePayment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt
Added optional payment confirmation button for native APM implementations: Views, Compose, Dynamic Checkout.
Button is visible when enabled in configuration and there is required customer action during capture stage.
Clicking on the button starts capture polling.
Added `DidConfirmPayment` event which is sent on button click.
[napm_paid_button_compose.webm](https://github.com/user-attachments/assets/685d2986-79b4-46c6-abad-9622ba031b3d)
[napm_paid_button_views.webm](https://github.com/user-attachments/assets/5745c5a3-39e5-4018-9c62-4b12480d5d71)
[dc_paid_button.webm](https://github.com/user-attachments/assets/7350640f-da6b-443d-a892-e182e6954f96)
https://checkout.atlassian.net/browse/POM-422
> feat(POM-422): Support nAPM payment confirmation

- sdk/src/main/res/values-ar/strings.xml
- sdk/src/main/res/values-fr/strings.xml
- sdk/src/main/res/values-pl/strings.xml
- sdk/src/main/res/values-pt/strings.xml
- sdk/src/main/res/values/strings.xml
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
[success.webm](https://github.com/user-attachments/assets/6bdb01e1-cf31-45d3-9704-8c7052fa7db7)
https://checkout.atlassian.net/browse/POM-418
> feat(POM-418): Dynamic Checkout success screen

- sdk/src/main/kotlin/com/processout/sdk/api/model/event/PODynamicCheckoutEvent.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/request/POCardTokenizationPreferredSchemeRequest.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/request/PONativeAlternativePaymentMethodDefaultValuesRequest.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/InvoiceResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCardTokenizationPreferredSchemeResponse.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodDefaultValuesResponse.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
Refactored:
1) Added `val original: PODynamicCheckoutPaymentMethod` to all internal `PaymentMethod` interactor types. It is needed for lifecycle events and make it easy to access the original type without the need to lookup for it.
2) Changed `DynamicCheckoutInteractorState` to keep the whole `PaymentMethod` object instead of only IDs for the following states (allows to avoid lookup for the object by id and simplifies the logic):
selectedPaymentMethodId -> selectedPaymentMethod
processingPaymentMethodId -> processingPaymentMethod
pendingSubmitPaymentMethodId -> pendingSubmitPaymentMethod
3) Refactored startup concurrency to send lifecycle events at correct moment.
4) Extracted some methods for readability.
Added:
1) `PODynamicCheckoutEvent` and sending all lifecycle events.
2) …
> feat(POM-419): Dynamic Checkout lifecycle events

- example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutFragment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
Swap `threeDSService` and `delegate` params order in PODynamicCheckoutLauncher
> fix(ad-hoc): PODynamicCheckoutLauncher improvement

- sdk/src/main/kotlin/com/processout/sdk/api/model/event/PODynamicCheckoutEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
Removed `paymentMethod` from `DidCompletePayment` event as we don't know what method was used if invoice is already captured on DC start. Event will be sent in this case as well.
> fix(ad-hoc): Fix DidCompletePayment event on DC

- build.gradle
- gradle/wrapper/gradle-wrapper.properties
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
Move success screen crossfade out of main scrollable container, so it doesn't jump during transition if content is scrolled.
Compose `2024.11.00`
**Bug:**
[success_bug.webm](https://github.com/user-attachments/assets/d61d4e7a-0593-4dca-abb0-fce704f4b5d0)
**Fixed:**
[success_fixed.webm](https://github.com/user-attachments/assets/0c8c87f3-4586-4eb7-9de0-c59f760d017b)
https://checkout.atlassian.net/browse/POM-438
> fix(POM-438): (DC) Fix transition to success screen

- sdk/src/main/kotlin/com/processout/sdk/api/network/interceptor/BasicAuthInterceptor.kt
- sdk/src/main/kotlin/com/processout/sdk/api/network/interceptor/RetryInterceptor.kt
- sdk/src/main/kotlin/com/processout/sdk/api/network/interceptor/UserAgentInterceptor.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/BaseRepository.kt
- sdk/src/main/kotlin/com/processout/sdk/di/NetworkGraph.kt
* Include `Idempotency-Key` header only with POST requests.
* Move retry logic from `BaseRepository` to `RetryInterceptor` so initial request remains the same on each retry, effectively ensuring that idempotency key is the same on POST retries.
https://checkout.atlassian.net/browse/POM-441
> feat(POM-441): Revise requests retry

- example/src/main/kotlin/com/processout/example/ui/screen/card/payment/CardPaymentFragment.kt
- example/src/main/kotlin/com/processout/example/ui/screen/checkout/DynamicCheckoutFragment.kt
- example/src/main/kotlin/com/processout/example/ui/screen/features/FeaturesFragment.kt
- sdk/src/main/res/values-ar/strings.xml
- sdk/src/main/res/values-fr/strings.xml
- sdk/src/main/res/values-pl/strings.xml
- sdk/src/main/res/values-pt/strings.xml
- sdk/src/main/res/values/strings.xml
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POActionsContainer.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/POButton.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/state/POActionState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/POCardUpdateConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/NativeAlternativePayment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/configuration/POBarcodeConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/configuration/POCancellationConfiguration.kt
* Added optional icon to `POButton`. Icon color always match to the text color in all states.
* Updated all screen configurations to be able to set custom icon on any button. Previous constructors deprecated.
* Added confirmation dialog to all Cancel buttons. Added strings.
* Unified `POCancellationConfiguration`, now it used on all bottom sheets. Duplicates and `secondaryAction` property is deprecated.
* Added `saveButton` to `POBarcodeConfiguration`.
* Added `cancelOnBackPressed` property to Dynamic Checkout configuration.
https://checkout.atlassian.net/browse/POM-442
> feat(POM-442): Extend screens customization options

- build.gradle
- ui/src/main/kotlin/com/processout/sdk/ui/base/BaseBottomSheetDialogFragment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/configuration/POBottomSheetConfiguration.kt
* Added generic `POBottomSheetConfiguration` which allows to set height as wrap content or fixed (in range 50-100%), expandable and cancellation.
* Applied to `POCardTokenizationConfiguration` and screen.
* Renamed `isCardholderNameFieldVisible` to `cardholderNameRequired` in new constructor.
* Updated libraries.
[wrap_content.webm](https://github.com/user-attachments/assets/e6b9ab81-76db-47f8-8f68-821309cf269a)
https://checkout.atlassian.net/browse/POM-451
> feat(POM-451): (Card Tokenization) Adjustable bottom sheet height

- .idea/kotlinc.xml
- build.gradle
- example/src/main/kotlin/com/processout/example/ui/screen/features/FeaturesFragment.kt
- gradle/wrapper/gradle-wrapper.properties
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/POCardUpdateConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/POSavedPaymentMethodsConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsViewModel.kt
* `POBottomSheetConfiguration` applied to Card Update and Saved Payment Methods screens.
* Saved Payment Methods screen wraps content by default and keeps minimum height at 38% of the screen.
[dc_saved_methods_wrap_content.webm](https://github.com/user-attachments/assets/7933284f-36a1-4936-8d86-98e25c08aff0)
https://checkout.atlassian.net/browse/POM-451
> feat(POM-451): Adjustable bottom sheet height

- ui/src/main/kotlin/com/processout/sdk/ui/base/BaseBottomSheetDialogFragment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/POSavedPaymentMethodsLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsActivityContract.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsInteractor.kt
* Finish SavedPaymentMethods on DC before transition to Success.
* AnimatedContent on DC instead of Crossfade and custom animations.
* SavedPaymentMethods bottom sheet height and animation adjustment.
Bug:
[bug.webm](https://github.com/user-attachments/assets/0b40fab9-588c-4e92-9b2e-a8e08b1e8cc8)
Fixed:
[fixed.webm](https://github.com/user-attachments/assets/d3e89eb3-4a0f-44fc-a663-87bbba25ef1a)
> fix(ad-hoc): Finish SavedPaymentMethods on DC before transition to Success

- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/PODialog.kt
* Workaround to enable edge-to-edge for Compose dialog. Note: scrim still doesn't cover status bar on some Android versions, but it always covers navigation bar and fixes enter transition glitch, which overall looks good.
* Custom enter animation.
Bug:
[dialog_bug.webm](https://github.com/user-attachments/assets/37438f89-191b-4a50-9f08-9808cd27e392)
Fixed:
[dialog_fixed.webm](https://github.com/user-attachments/assets/3c9bbc79-ecfa-44fb-8c0c-e29719014191)
> fix(ad-hoc): Edge-to-edge dialog

- build.gradle
- sdk/src/main/kotlin/com/processout/sdk/api/model/event/POSavedPaymentMethodsEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/CardUpdateViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/POSavedPaymentMethodsConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/POSavedPaymentMethodsDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/POSavedPaymentMethodsLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/savedpaymentmethods/SavedPaymentMethodsInteractor.kt
Standalone SavedPaymentMethods screen is ready for release:
* Added logs and docs.
* Dispatching events.
* Removed ProcessOutInternalApi annotation from related classes.
Misc:
* `Dismiss` log level changed from `warn` to `info` on all screens.
* Updated libs.
> feat(ad-hoc): SavedPaymentMethods finalization

- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
Added Dynamic Checkout logs
https://checkout.atlassian.net/browse/POM-431
> feat(POM-431): Dynamic Checkout logs

- .idea/kotlinc.xml
- build.gradle
- example/src/main/AndroidManifest.xml
- example/src/main/kotlin/com/processout/example/ui/screen/card/payment/CardPaymentFragment.kt
- sdk/src/main/res/values-ar/strings.xml
- sdk/src/main/res/values-fr/strings.xml
- sdk/src/main/res/values-pl/strings.xml
- sdk/src/main/res/values-pt/strings.xml
- sdk/src/main/res/values/strings.xml
- ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/scanner/CardScannerViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutEvent.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/CardTokenization.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/DynamicCheckoutScreen.kt
- ui/src/main/res/drawable/po_icon_camera.xml
Card scanner integration with Card Tokenization and Dynamic Checkout.
https://github.com/user-attachments/assets/29bcf80a-1767-4c7c-893f-6076d6e71dff
**Misc:**
* `lateinit var` for `POCardTokenizationConfiguration` and `PODynamicCheckoutConfiguration` on respective screens to simplify usage and avoid duplicated defaults.
* Kotlin `2.1.20`
* Added logs.
* Added OCR metadata to Example app AndroidManifest.
https://checkout.atlassian.net/browse/POM-457
> feat(POM-457): Integrate card scanner

- example/src/main/kotlin/com/processout/example/ui/screen/card/payment/DefaultCardTokenizationDelegate.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCardScheme.kt
- sdk/src/main/kotlin/com/processout/sdk/api/repository/ApiFailureMapper.kt
- sdk/src/main/kotlin/com/processout/sdk/core/ProcessOutResult.kt
- sdk/src/main/kotlin/com/processout/sdk/ui/nativeapm/NativeAlternativePaymentMethodViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModelState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/CardTokenization.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/extension/EnumExtensions.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/CardSchemeDrawableResProvider.kt
- ui/src/main/kotlin/com/processout/sdk/ui/shared/provider/CardSchemeProvider.kt
* Preferred scheme selection on Card Tokenization and Dynamic Checkout.
* Added `POCardScheme` enum with `rawValue` and `displayName` mapping. Enum is used in `CardSchemeProvider`, `CardSchemeDrawableResProvider` and for preferred scheme selection.
* Added `localizedMessage` to `ProcessOutResult.Failure`. It can be used to show custom external error message while processing tokenized card.
https://github.com/user-attachments/assets/9aa7190c-761c-4758-a570-7e0421951487
https://checkout.atlassian.net/browse/POM-472
> feat(POM-472): (Card Tokenization & DC) Preferred scheme selection

- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
* `PODefaultCardTokenizationEventDispatcher` is removed from DC, instead using `POEventDispatcher` directly.
* Restored card payment functionality.
https://checkout.atlassian.net/browse/POM-480
> feat(POM-480): (Dynamic Checkout) Remove card dispatcher

- sdk/src/main/kotlin/com/processout/sdk/api/model/response/POCardScheme.kt
Updated `POCardScheme` and display names.
> feat(ad-hoc): Update card schemes and display names

- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmFragment.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentLauncher.kt
* Introduced `PONativeAlternativePaymentDelegate` instead of `PONativeAlternativePaymentMethodEventDispatcher`.
* `PONativeAlternativePaymentMethodEventDispatcher` is removed from DC, instead using `POEventDispatcher` directly.
* Refactored nAPM default values functionality.
https://checkout.atlassian.net/browse/POM-470
> feat(POM-470): (nAPM & DC) Migrate dispatcher to delegate

- build.gradle
- sdk/build.gradle
- sdk/src/main/kotlin/com/processout/sdk/api/model/request/PODynamicCheckoutAlternativePaymentDefaultValuesRequest.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/PONativeAlternativePaymentMethodDefaultValuesResponse.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/update/POCardUpdateDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/dispatcher/DynamicCheckoutAlternativePaymentConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/dispatcher/DynamicCheckoutSavedPaymentMethods.kt
* Allow to override default nAPM configuration for specific payment method via delegate.
* Refactored nAPM `defaultValues()` function in delegate to propagate `paymentMethod` instead of `gatewayConfigurationId`.
* Removed unnecessary `suspend` modifier from some functions in delegates.
* Added explicit coroutines dependency to avoid conflicts: `org.jetbrains.kotlinx:kotlinx-coroutines-android`
https://checkout.atlassian.net/browse/POM-476
> feat(POM-476): (Dynamic Checkout) Support nAPM config for specific payment method

- .idea/codeStyles/Project.xml
- build.gradle
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/POField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/dropdown/PODropdownField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/dropdown/POLabeledDropdownField.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/radio/PORadioGroup.kt
- ui-core/src/main/kotlin/com/processout/sdk/ui/core/component/field/text/POTextField.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationInteractorState.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationScreen.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/CardTokenizationViewModel.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/POCardTokenizationLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/delegate/CardTokenizationEligibility.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/delegate/POCardTokenizationDelegate.kt
- ui/src/main/kotlin/com/processout/sdk/ui/card/tokenization/delegate/POCardTokenizationEligibility.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/PODynamicCheckoutLauncher.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/screen/CardTokenization.kt
* Added card eligibility evaluation via delegate.
* Disabling all fields and card scanner button while submitting for consistent logic.
* IIN length changed from 6 to 8 for logic in interactor.
* Updating preferred scheme by local issuer information when IIN length < 8.
* Applied related changes on Dynamic Checkout.
https://github.com/user-attachments/assets/32bf0d41-1ff7-4f0f-9ac8-cacc254e0381
https://checkout.atlassian.net/browse/POM-477
> feat(POM-477): (Card Tokenization) Card eligibility evaluation

- sdk/src/main/kotlin/com/processout/sdk/api/model/response/napm/v2/PONativeAlternativePaymentElement.kt
- sdk/src/main/kotlin/com/processout/sdk/api/model/response/napm/v2/PONativeAlternativePaymentRedirect.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentViewModel.kt
* AvailableValue: `key` -> `value`
* PONativeAlternativePaymentRedirect: non-nullable `hint`
> fix(ad-hoc): API response adjustments

- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmFragment.kt
- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmUiState.kt
- example/src/main/kotlin/com/processout/example/ui/screen/nativeapm/NativeApmViewModel.kt
- example/src/main/res/layout/fragment_native_apm.xml
- example/src/main/res/values/strings.xml
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutActivity.kt
- ui/src/main/kotlin/com/processout/sdk/ui/checkout/DynamicCheckoutInteractor.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/NativeAlternativePaymentBottomSheet.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/PONativeAlternativePaymentConfiguration.kt
- ui/src/main/kotlin/com/processout/sdk/ui/napm/v2/NativeAlternativePaymentInteractor.kt
* Added `Flow` to `PONativeAlternativePaymentConfiguration`. Deprecated previous constructor. Updated affected code.
* Added tokenize nAPM flow in example app.
> feat(ad-hoc): Tokenize nAPM flow in example app

- .github/workflows/create-release-and-publish.yml
- .github/workflows/create-release-candidate.yml
- .github/workflows/release-documentation.yml
- .github/workflows/run-tests.yml
- build.gradle
- checkout-3ds/build.gradle
- checkout-3ds/src/main/kotlin/com/processout/sdk/checkout/threeds/POCheckout3DSService.kt
- example/build.gradle
- example/src/main/res/raw/keep.xml
- gradle/wrapper/gradle-wrapper.properties
- netcetera-3ds-core/build.gradle
- netcetera-3ds-core/dexguard.txt
- netcetera-3ds/build.gradle
- netcetera-3ds/consumer-rules.pro
- netcetera-3ds/src/main/kotlin/com/processout/sdk/netcetera/threeds/Netcetera3DS2ServiceState.kt
- netcetera-3ds/src/main/kotlin/com/processout/sdk/netcetera/threeds/PONetcetera3DS2Service.kt
- netcetera-3ds/src/main/kotlin/com/processout/sdk/netcetera/threeds/PONetcetera3DS2ServiceConfiguration.kt
- netcetera-3ds/src/main/kotlin/com/processout/sdk/netcetera/threeds/PONetcetera3DS2ServiceDelegate.kt
- netcetera-3ds/src/main/res/drawable/po_logo_placeholder.xml
- sdk/build.gradle
- sdk/src/main/kotlin/com/processout/sdk/api/service/DefaultCustomerActionsService.kt
- ui-core/build.gradle
- ui/build.gradle
* Netcetera 3DS service and module.
* Updated minor dependencies.
* Updated Github workflows.
https://checkout.atlassian.net/browse/POM-503
https://checkout.atlassian.net/browse/POM-502
> feat(POM-503): Netcetera 3DS service and module

- sdk/src/main/kotlin/com/processout/sdk/api/ProcessOutConfiguration.kt
> fix(ad-hoc): Enable telemetry by default
